const appname = "Easy Buy";
const appversion = "Version 1.0.0";
const credits = "@Aayush Gupta";
const email = "Email";
const emailhint = "abc@gmail.com";
const password = "Password";
const passwordHint = "*******";
const confirmPassword = "Confirm Password";
const name = "Name";
const nameHint = "Aayush";
const forgetPassword = "Forget Password";
const login = "login";
const signup = "Sign Up";
const createNewAccount = "or ,Create New Account";
const LoginWith = "Log in With";
const signUpWith = "Sign Up With";
const alreadyHaveAnAccount = "Already Have an account";
const home = "home";
const categories = "Categories";
const cart = "Cart";
const account = "Account";
const searchAnything = "Search Anything..",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSeller = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womensDress = "Women Dress",
    girlsWatches = "Girls Watch",
    mobilePhones = "Mobile Phones",
    boysGlasses = "Boys Glasses",
    girlsDresse = "Girls Dress",
    tShirts = "T-Shirts",
    featuredProducts = "Featured Products",
    featuredCategories = "FeaturedCategories";

const womenClothing = "Women CLothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidtoys = "Kid Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
const video = "Video",
    review = "Reviews",
    supportpolicy = "Support Policy",
    returnpolicy = "Return Policy",
    privacypolicy = "privacy Policy",
    productsYouMayAlsoLike = "Products You May Also Like";
const logout="Logout",wishlist="My Wishlisht",orders="My Orders",messages="Messages";
